### ISSUE TITLE
Add support for launchConfiguration type = "org.eclipse.pde.ui.RuntimeWorkbench"

### ISSUE THREAD

**Issue by otopba** [kukido/eclipser#18] opened 2015-07-26 17:13 UTC
Please add support for type "org.eclipse.pde.ui.RuntimeWorkbench"

**Comment by kukido** [comment] 2015-08-03 04:56
This request is a duplicate of #15. 
`RuntimeWorkbench` is Eclipse application itself. There's no Eclipse runner in IntelliJ for obvious reasons, hence the plugin does not support this kind of launchers.

**Closed by kukido** 2015-08-03 04:56 UTC
